### ISSUE TITLE
Fix the tooltip for generate points by grid size node

### ISSUE THREAD

**Issue by teabaker** [ladybug-tools/honeybee-plus#41]
Hi!
I have been using the Ladybug Generate Test Points node to perform a daylight factor analysis. It works fine, but as soon as I switch to the Honeybee Generate Test Points by Grid Size node and run the script, Dynamo stops responding. I am using exactly the same inputs and outputs and have merely generated polygons from the test surfaces for the _borders input.
Any ideas? I would like to use the polygons output from the Honeybee node.
Thanks!
![screenshot for github](https://cloud.githubusercontent.com/assets/25978191/23652838/a4098e9e-032a-11e7-831d-87d025e17ee4.png)

**Comment by mostaphaRoudsari** [comment]
@teabaker I guess 100 is a very small gridsize based on the units of your document. Use a larger value for grid size and it should work fine.

**Comment by teabaker** [comment]
Ah I see!

I think I was confused as gridSize and numOfSegments both show the same text when you hover over them, so I assumed the input was the same.

I increased the gridSize input to 1000 and it worked fine, thanks!

![11](https://cloud.githubusercontent.com/assets/25978191/23705202/0c99cae4-0409-11e7-93b6-b27b736b9ef3.png)
![12](https://cloud.githubusercontent.com/assets/25978191/23705208/11b4425c-0409-11e7-83af-f685c8c4409b.png)

**Comment by mostaphaRoudsari** [comment]
@teabaker Thanks for reporting this. Will get it fixed for the next release.

**Comment by mostaphaRoudsari** [comment]
Fixed in 1.1
