### ISSUE TITLE
Simulation Quality - What parameters does this set?

### ISSUE THREAD

**Issue by teabaker** [ladybug-tools/honeybee-plus#44]
Hi!

Sorry for the previous erroneous post 'Hi!'

My question is regarding the 'quality' input to the radiance parameters. What parameters does this set and will there be more manual inputs (such as ambient bounces) in a new release, or is there a way to specify at the moment?

Thanks!

![11](https://cloud.githubusercontent.com/assets/25978191/23753903/6d6237bc-04db-11e7-81f1-c09784c3df48.png)

**Comment by mostaphaRoudsari** [comment]
@teabaker [here](https://github.com/ladybug-tools/honeybee/blob/master/honeybee/radiance/parameters/_defaultset.py#L3-L18) is the list of all the parameters that are set based on quality input. There are 3 values for each parameter for low/medium/high quality.

You can change any of them or add new ones by using a Python component until we add an input to the node.
![image](https://cloud.githubusercontent.com/assets/2915573/23797393/a6277e58-056d-11e7-8bd7-62d297737afe.png)

**Comment by teabaker** [comment]
Thank you!
