### ISSUE TITLE
Error message from Honeybee: 

### ISSUE THREAD

**Issue by Mahamiho** [ladybug-tools/honeybee-plus#46]
Hey,
I am getting this error message from honeybee 'run radiance component' , any ideas on how to fix it? thanks :)
![error](https://cloud.githubusercontent.com/assets/26859104/24591175/63ae1550-17fb-11e7-9da3-17b70bb7fab7.PNG)

**Comment by mostaphaRoudsari** [comment]
Hi @Mahamiho, You need to install Radiance in `c:\radiance` and add it to system PATH.

**Comment by Mahamiho** [comment]
Hey,
Thanks for the quick reply. I already have radiance on C:\ but can you tell me how to add it to system PATH?

**Comment by mostaphaRoudsari** [comment]
http://windowsitpro.com/systems-management/how-can-i-add-new-folder-my-system-path

**Comment by Mahamiho** [comment]
Hey mostapha,
thanks alot for your reply, the problem is still not solved, i figured that my antivirus is blocking honeybee from reading radiance (somehow), i never experienced this problem before, but will try to fix it and come back with questions if it is not solved.

**Comment by mostaphaRoudsari** [comment]
Hi @Mahamiho, Thank you for the update. Should we close this issue?

**Comment by Mahamiho** [comment]
Yes, thanks alot for your help
