### ISSUE TITLE
Changing double glass to single in dynamo

### ISSUE THREAD

**Issue by Mahamiho** [ladybug-tools/honeybee-plus#47]
Hey,
is there an easy way to convert the double glass from revit to a single pane glass to be able to run accurate daylight simulations in honeybee? thanks alot,

**Comment by mostaphaRoudsari** [comment]
You can sort the surfaces by area and pick the one with the largest area.

Also the `Room To Zone` node does simplify the geometry to get a single pane glass.

**Comment by Mahamiho** [comment]
Great that worked, thanks alot
