### ISSUE TITLE
Run Radiance Simulation node in Dynamo 1.3 returns empty list

### ISSUE THREAD

**Issue by martinromby** [ladybug-tools/honeybee-plus#48]
After following the different tutorials and installing Radiance in C:\Radiance etc. I've ended up with that Run Radiance Simulation node is returning an empty list. 
![image](https://cloud.githubusercontent.com/assets/15892140/24944360/1a132630-1f5b-11e7-93b9-8fdb1bcd368a.png)
Any ideas of why this is happening? 

/Martin

**Comment by martinromby** [comment]
Reboot fixed the problem.

**Comment by Mahamiho** [comment]
Hey @mostaphaRoudsari I have the same problem now on a computer, the same file seems to work fine on another computer, any ideas why this could be happening? I tried to disable the antivirus and it did not help, and honeybee in grasshopper is working fine. The problem as I see it is that the simulation does not start running. Thanks alot

**Comment by mostaphaRoudsari** [comment]
@Mahamiho, Can you share the radiance folder? I just ran the analysis with now issues on version 1.3. No error message?
