### ISSUE TITLE
Can't find None\oconv.exe

### ISSUE THREAD

**Issue by SamDehghani** [ladybug-tools/honeybee-plus#52]
When running the sample "00_sunlighthours.dyn" I got this error message : "Can't find None\oconv.exe. use radbinPath method to set the path to radiance binaries before executing the command ...".
Thanks in advance

**Comment by mostaphaRoudsari** [comment]
Hi @SamDehghani, Check this [issue](https://github.com/ladybug-tools/honeybee-plus/issues/46#issuecomment-291016370).

**Comment by SamDehghani** [comment]
Thanks for the quick reply.
