### ISSUE TITLE
Saving the Honeybee results in Revit

### ISSUE THREAD

**Issue by Mahamiho** [ladybug-tools/honeybee-plus#53]
Hey,
I followed the previous discussions (below) on how to save the analysis grid results from Honeybee in Dynamo in Revit, but still could not manage to make it work. I was trying to generate the surfaces in Revit using 'import instance' instead of selecting the surfaces, and used the points from the 'Generate test points by grid size' node, does someone has an updated script to do it, or do you have comments on my script in the image?
https://github.co
![colour surface not working](https://cloud.githubusercontent.com/assets/26859104/26343281/9a97b946-3f9b-11e7-8138-97a210376523.PNG)
m/DynamoDS/Dynamo/issues/6454

**Comment by SamDehghani** [comment]
Hi Mahamiho,
I have devised a workflow to display Honeybee results directly in Revit. I've made a 5 minute tutorial and asked Mostapha Roodsari to kindly revise it. I'll keep you informed when the clip is ready to be published.

**Comment by Mahamiho** [comment]
Hey Sam,
Thanks alot for your reply, in the meantime can you share the script that you did, or a screen shot of it? I am working on a project and I really need a work around it.

**Comment by SamDehghani** [comment]
Hi Mahamiho,
The video link is : https://youtu.be/sF1wT3VCkI0
Have fun.

**Comment by mostaphaRoudsari** [comment]
@Mahamiho, did @SamDehghani's approach solved your problem?

**Comment by Mahamiho** [comment]
Hey @SamDehghani  and @mostaphaRoudsari thanks for your replies, I will check it out and let you know if I have problems

**Comment by mostaphaRoudsari** [comment]
[here](http://hydrashare.github.io/hydra/viewer?owner=SamDehghani&fork=hydra&id=Bake_Honeybee_Daylight_Results_from_Dynamo_to_Revit&slide=0&scale=1&offset=0,0) is the example file. Thanks @SamDehghani.

**Comment by schaggar16** [comment]
having a look at this script, is there a way we can get more control over the color settings - for example defining explicit values between the min and max?

**Comment by Mahamiho** [comment]
Hey @SamDehghani I have not managed to make the script to work, neither the legend nor the markers are shown in the 3D in Revit, I am not sure whats the problem as I am not getting any errors, Do you have ideas? Also where do you get the display style name that is loaded in the marker and text display style? because I think that can be a factor in the problem. Thanks alot,
![saving results in revit is not working](https://user-images.githubusercontent.com/26859104/26877427-3e941d42-4b8a-11e7-94f7-c21253f913aa.PNG)

**Comment by SamDehghani** [comment]
Hi @Mahamiho , it seems to me that "Legend Setting" is not working properly. please attach (true or false) to "Show Data description". I hope it solves the problem.

**Comment by mostaphaRoudsari** [comment]
Here is [both methods](http://hydrashare.github.io/hydra/?keywords=samDehghani). Thanks @SamDehghani!

**Comment by jrthill1** [comment]
I am having the same issue, neither my legend or markers show up in Revit. Could it have something do to with the "null" from the Get Text Note by Name node? Thank you!

![image](https://user-images.githubusercontent.com/46583665/69921254-e1207d80-1455-11ea-899f-7cb009a46c97.png)
