### ISSUE TITLE
Epw files for Brazil cities generate errors when trying to create sky matrix 

### ISSUE THREAD

**Issue by arqpml** [ladybug-tools/honeybee-plus#54]
Whenever I try to use an epw from Brazil (same results for Rio de Janeiro, Salvador and Sao Paulo) it generates an error and does not complete the sky matrix (this happens in grasshopper and also in Dynamo):
Below is the error message in dynamo (tried with Paris, works fine):
Also, I've attached the epw file from salvador.
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\Users\Pablo\AppData\Roaming\Dynamo\Dynamo Revit\1.2\packages\Ladybug\extra\ladybugdynamo\ladybug\sky.py", line 395, in gendaymtx
    self.__loadMtxFiles()
  File "C:\Users\Pablo\AppData\Roaming\Dynamo\Dynamo Revit\1.2\packages\Ladybug\extra\ladybugdynamo\ladybug\sky.py", line 358, in _CumulativeSkyMtx__loadMtxFiles
    assert self.__isCalculated, "You need to calculate the materix first before" + \
AssertionError: You need to calculate the materix first before loading the results. Use calculateMtx method. If you see this error from inside Dynamo reconnect one of the inputs and re-run the file!
[Salvador.zip](https://github.com/ladybug-tools/honeybee-plus/files/1027641/Salvador.zip)

Thanks!

**Comment by mostaphaRoudsari** [comment]
Hi @arqpml, Thanks for reporting this. This is most probably because of the special character in location name. Let me see if there is an easy solution for this and report back.

![image](https://cloud.githubusercontent.com/assets/2915573/26523959/12747c6a-42f3-11e7-85eb-8eb0c0921f23.png)

**Comment by mostaphaRoudsari** [comment]
Fixed! I will push a new version of Ladybug to package manager soon which should address this issue.
![image](https://cloud.githubusercontent.com/assets/2915573/26524214/d608c0a4-42f9-11e7-8ff2-025823f46e64.png)
