### ISSUE TITLE
Problem with Honeybee Surfaces: 'Index out of range: 1'

### ISSUE THREAD

**Issue by teabaker** [ladybug-tools/honeybee-plus#56]
Hi,

I've just updated Honeybee to version 1.1 and I'm receiving the following error report from Honeybee Surface nodes:

![error](https://cloud.githubusercontent.com/assets/25978191/26637356/90ce9fe4-461f-11e7-89d2-a818fbbccc93.png)

My inputs to the node are a list of surfaces and a Radiance Material specified using some Python code (provided through GitHub on a previous issue), see below:

![error2](https://cloud.githubusercontent.com/assets/25978191/26637546/0a1a9c22-4620-11e7-9d6e-2028fb4cb336.png)

I can attach the file if needed. Any ideas on what the problem is? :D

Thanks!

**Comment by schaggar16** [comment]
had a similar issue. by setting a type and name it seems to run fine

**Comment by mostaphaRoudsari** [comment]
It's fixed now. Also added a node for opaque material. Thanks for reporting.

![image](https://user-images.githubusercontent.com/2915573/26891741-0f18887e-4b84-11e7-9dfc-fab037bc5c4a.png)
